# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66rame_message.proto\x12\tstreaming\"\xb6\x01\n\x0c\x46rameMessage\x12\x18\n\x0bvideo_bytes\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x18\n\x0b\x61udio_bytes\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x19\n\x0cstart_speech\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12\x17\n\nend_speech\x18\x04 \x01(\x08H\x03\x88\x01\x01\x42\x0e\n\x0c_video_bytesB\x0e\n\x0c_audio_bytesB\x0f\n\r_start_speechB\r\n\x0b_end_speechb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FRAMEMESSAGE._serialized_start=35
  _FRAMEMESSAGE._serialized_end=217
# @@protoc_insertion_point(module_scope)
